site_name: PARAM SHAVAK 2.0 User Manual
site_description: User and Administrator Manual for PARAM SHAVAK 2.0
site_author: C-DAC

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - toc.follow

  logo: image/cdac-logo.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.tasklist:
      custom_checkbox: true

  - attr_list
  - md_in_html
  - tables

  - toc:
      permalink: true

plugins:
  - search

nav:

  - Home:
      - Introduction: index.md
      - Key feature: keyfeature.md

  - System Overview:
      - System Overview: overview/system-overview.md
      - System Requirements and Variants: overview/system-requirements.md
      - Architecture: overview/architecture.md

  - Unboxing And Startup Guide:
      - Uboxing : Guide/unbox.md
      - Port Guide : Guide/port.md
      - Power up : Guide/powerup.md

  - Operating System :
      - HPC Overview: OS/Overview.md
      - User Interface : OS/Interface.md

  - Administration:
      - Basic System Check: Admin/system_check.md
      - User Creaton Cli: Admin/user-creation-cli.md
      - User Creaton Gui: Admin/user-creation-gui.md
      - User Management Cli: Admin/user-management-cli.md
      - User Management Gui: Admin/user-management-gui.md

  - Basic Commands and HPC Applications:
      - Installed Applications: applications/application-list.md
      - Basic Linux Commands : applications/commands.md
      - Slurm : applications/slurm.md
      - HPC GUI : applications/hpcgui.md

  - Remote Login:
      - Remote Access : Login/Linux.md

  - Reference:  
      - Important Facts: reference.md

  - Help and Support:
      - Help: support/help.md
      - Support: support/support.md